### ISSUE TITLE
how start?

### ISSUE THREAD

**Issue by denis-vk** [xBidi/PancakeSwapBot#10]
root@Ubuntu-2004-focal-64-minimal ~/PancakeSwapBot # npm start

> pancakeswap@1.0.0 start
> ts-node src/bot.ts

Bot started at 9:05
/root/PancakeSwapBot/node_modules/@ethersproject/logger/src.ts/index.ts:225
        const error: any = new Error(message);
                           ^
Error: call revert exception (method="currentEpoch()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at Logger.makeError (/root/PancakeSwapBot/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/root/PancakeSwapBot/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Interface.decodeFunctionResult (/root/PancakeSwapBot/node_modules/@ethersproject/abi/src.ts/interface.ts:425:23)
    at Contract.<anonymous> (/root/PancakeSwapBot/node_modules/@ethersproject/contracts/src.ts/index.ts:392:44)
    at step (/root/PancakeSwapBot/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/root/PancakeSwapBot/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/root/PancakeSwapBot/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'currentEpoch()',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x6e17072D6B2524aBB63134c632144F59Ca0aebbF',
  args: [],
  transaction: {
    data: '0x76671808',
    to: '0x6e17072D6B2524aBB63134c632144F59Ca0aebbF',
    from: '0x6e17072D6B2524aBB63134c632144F59Ca0aebbF'
  }
}

**Comment by philipoolivier** [comment]
you have to leave the ppv2 address in the env file. I think that is the smart contract address.
